### ISSUE TITLE
Attempt to unlock without a lock

### ISSUE THREAD

**Issue by tibers** [lookout/cassandra-health-check#6]
Hi folks. I'm no cassandra expert (or java guy) but I believe I've found an issue. I am invoking the jar file as follows:
> java -jar /opt/xymon/server/ext/cassandra-health-check-1.0.0-all.jar -host 10.1.16.17 -port 9042 -username cassandra -password cassandra

We had a firewall problem which cut the jar files access to the server. When we fixed the firewalls, the client started throwing the following error. Any help is appreciated. 

> 09:14:17.158 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.1.16.15:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.11.16.25:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.1.16.17:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.1.16.16:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.1.16.19:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.1.16.18:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.11.16.27:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.11.16.26:9042 added
> 09:14:17.166 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.11.16.15:9042 added
> 09:14:17.167 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.11.16.14:9042 added
> 09:14:17.167 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.11.16.13:9042 added
> 09:14:17.167 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.1.16.10:9042 added
> 09:14:17.358 [cluster1-nio-worker-1] INFO  c.l.cassandra.LoggingLatencyTracker - Host /10.1.16.17:9042 latency 26ms
> Exception in thread "main" java.lang.IllegalStateException: Attempt to unlock without a lock
at com.lookout.cassandra.CrossJVMLock.unlock(CrossJVMLock.java:48)
at com.lookout.cassandra.CassandraHealthCheck.shutdown(CassandraHealthCheck.java:234)
at com.lookout.cassandra.CassandraHealthCheck.main(CassandraHealthCheck.java:113)

**Comment by thedebugger** [comment]
@tibers were you able to figure out what happened? If no, I can help. Let us know.

**Comment by tibers** [comment]
Nope, never figured it out. I am open to suggestions!

**Comment by rkuris** [comment]
@tibers Which version of Cassandra are you using? Also, can you send the output of nodetool status so I can see if all the nodes are in the list above?

**Comment by rkuris** [comment]
Looks like this error might be possible if the lockfile cannot be created in the java temporary directory. It's called healthchk.lck.

**Comment by rkuris** [comment]
One more thought: can you run this with "-debug" on the command line? That might provide another clue.

**Comment by thedebugger** [comment]
After looking at the above exception carefully, it seems like a side effect of the problem as it is trying to unlock on shut down. But, we can't tell why it is shutting down. '-debug` might help here.

**Comment by tibers** [comment]
I hate to say this but it seems to have solved itself...
